<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TableFootballMatchesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('table_football_matches')->delete();
        
        \DB::table('table_football_matches')->insert(array (
            0 => 
            array (
                'match_id' => 1,
                'team_first' => 'Manchester City',
                'team_second' => 'Sheffield United',
                'season' => '2023/2024',
                'tour' => 'tour 3',
                'match_date' => '2023-08-27',
                'coefficient_team_first' => 1.21,
                'coefficient_draw' => 7.0,
                'coefficient_team_second' => 19.0,
                'team_first_goals' => 2,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-11 18:23:54',
                'updated_at' => '2024-08-11 18:23:54',
            ),
            1 => 
            array (
                'match_id' => 2,
                'team_first' => 'West Ham United',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 5',
                'match_date' => '2023-09-16',
                'coefficient_team_first' => 6.5,
                'coefficient_draw' => 4.8,
                'coefficient_team_second' => 1.5,
                'team_first_goals' => 1,
                'team_second_goals' => 3,
                'result' => 'win_second',
                'created_at' => '2024-08-11 18:27:46',
                'updated_at' => '2024-08-11 18:27:46',
            ),
            2 => 
            array (
                'match_id' => 3,
                'team_first' => 'Manchester City',
                'team_second' => 'Forest',
                'season' => '2023/2024',
                'tour' => 'tour 6',
                'match_date' => '2023-09-23',
                'coefficient_team_first' => 1.17,
                'coefficient_draw' => 8.0,
                'coefficient_team_second' => 20.0,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-11 18:32:17',
                'updated_at' => '2024-08-11 18:32:17',
            ),
            3 => 
            array (
                'match_id' => 4,
                'team_first' => 'Wolverhampton',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 7',
                'match_date' => '2023-09-30',
                'coefficient_team_first' => 9.0,
                'coefficient_draw' => 5.4,
                'coefficient_team_second' => 1.37,
                'team_first_goals' => 2,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-11 18:35:35',
                'updated_at' => '2024-08-11 18:35:35',
            ),
            4 => 
            array (
                'match_id' => 5,
                'team_first' => 'Manchester City',
                'team_second' => 'Arsenal',
                'season' => '2023/2024',
                'tour' => 'tour 8',
                'match_date' => '2023-10-08',
                'coefficient_team_first' => 2.53,
                'coefficient_draw' => 3.55,
                'coefficient_team_second' => 3.05,
                'team_first_goals' => 0,
                'team_second_goals' => 1,
                'result' => 'win_second',
                'created_at' => '2024-08-11 21:51:03',
                'updated_at' => '2024-08-11 21:51:03',
            ),
            5 => 
            array (
                'match_id' => 6,
                'team_first' => 'Manchester City',
                'team_second' => 'Bournemounth',
                'season' => '2023/2024',
                'tour' => 'tour 11',
                'match_date' => '2023-11-04',
                'coefficient_team_first' => 1.12,
                'coefficient_draw' => 10.0,
                'coefficient_team_second' => 28.0,
                'team_first_goals' => 6,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-11 23:07:03',
                'updated_at' => '2024-08-11 23:07:03',
            ),
            6 => 
            array (
                'match_id' => 7,
                'team_first' => 'Chelsea',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 12',
                'match_date' => '2023-11-12',
                'coefficient_team_first' => 5.2,
                'coefficient_draw' => 3.9,
                'coefficient_team_second' => 1.8,
                'team_first_goals' => 4,
                'team_second_goals' => 4,
                'result' => 'draw',
                'created_at' => '2024-08-11 23:10:31',
                'updated_at' => '2024-08-11 23:10:31',
            ),
            7 => 
            array (
                'match_id' => 8,
                'team_first' => 'Aston Villa',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 15',
                'match_date' => '2023-12-06',
                'coefficient_team_first' => 4.5,
                'coefficient_draw' => 4.25,
                'coefficient_team_second' => 1.75,
                'team_first_goals' => 1,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-11 23:13:12',
                'updated_at' => '2024-08-11 23:13:12',
            ),
            8 => 
            array (
                'match_id' => 9,
                'team_first' => 'Luton town',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 16',
                'match_date' => '2023-12-10',
                'coefficient_team_first' => 19.5,
                'coefficient_draw' => 8.1,
                'coefficient_team_second' => 1.17,
                'team_first_goals' => 1,
                'team_second_goals' => 2,
                'result' => 'win_second',
                'created_at' => '2024-08-11 23:14:59',
                'updated_at' => '2024-08-11 23:14:59',
            ),
            9 => 
            array (
                'match_id' => 10,
                'team_first' => 'Manchester City',
                'team_second' => 'Crystal Palace',
                'season' => '2023/2024',
                'tour' => 'tour 17',
                'match_date' => '2023-12-16',
                'coefficient_team_first' => 1.21,
                'coefficient_draw' => 7.3,
                'coefficient_team_second' => 16.5,
                'team_first_goals' => 2,
                'team_second_goals' => 2,
                'result' => 'draw',
                'created_at' => '2024-08-11 23:18:00',
                'updated_at' => '2024-08-11 23:18:00',
            ),
            10 => 
            array (
                'match_id' => 11,
                'team_first' => 'Manchester City',
                'team_second' => 'Sheffield United',
                'season' => '2023/2024',
                'tour' => 'tour 20',
                'match_date' => '2023-12-30',
                'coefficient_team_first' => 1.1,
                'coefficient_draw' => 11.0,
                'coefficient_team_second' => 37.0,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-11 23:21:24',
                'updated_at' => '2024-08-11 23:21:24',
            ),
            11 => 
            array (
                'match_id' => 12,
                'team_first' => 'Manchester City',
                'team_second' => 'Newcastle United',
                'season' => '2023/2024',
                'tour' => 'tour 21',
                'match_date' => '2024-01-12',
                'coefficient_team_first' => 1.61,
                'coefficient_draw' => 4.4,
                'coefficient_team_second' => 5.6,
                'team_first_goals' => 3,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-11 23:24:12',
                'updated_at' => '2024-08-11 23:24:12',
            ),
            12 => 
            array (
                'match_id' => 13,
                'team_first' => 'Burnley',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 22',
                'match_date' => '2024-01-12',
                'coefficient_team_first' => 31.0,
                'coefficient_draw' => 10.0,
                'coefficient_team_second' => 1.12,
                'team_first_goals' => 1,
                'team_second_goals' => 3,
                'result' => 'win_second',
                'created_at' => '2024-08-11 23:26:46',
                'updated_at' => '2024-08-11 23:26:46',
            ),
            13 => 
            array (
                'match_id' => 14,
                'team_first' => 'Manchester City',
                'team_second' => 'Everton',
                'season' => '2023/2024',
                'tour' => 'tour 24',
                'match_date' => '2024-02-10',
                'coefficient_team_first' => 1.24,
                'coefficient_draw' => 7.0,
                'coefficient_team_second' => 13.0,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-11 23:28:12',
                'updated_at' => '2024-08-11 23:28:12',
            ),
            14 => 
            array (
                'match_id' => 15,
                'team_first' => 'Manchester City',
                'team_second' => 'Chelsea',
                'season' => '2023/2024',
                'tour' => 'tour 25',
                'match_date' => '2024-02-17',
                'coefficient_team_first' => 1.37,
                'coefficient_draw' => 5.6,
                'coefficient_team_second' => 8.5,
                'team_first_goals' => 1,
                'team_second_goals' => 1,
                'result' => 'draw',
                'created_at' => '2024-08-11 23:29:44',
                'updated_at' => '2024-08-11 23:29:44',
            ),
            15 => 
            array (
                'match_id' => 16,
                'team_first' => 'Burnley',
                'team_second' => 'Manchester City',
                'season' => '2023/2024',
                'tour' => 'tour 1',
                'match_date' => '2023-08-11',
                'coefficient_team_first' => 10.0,
                'coefficient_draw' => 5.7,
                'coefficient_team_second' => 1.33,
                'team_first_goals' => 0,
                'team_second_goals' => 3,
                'result' => 'win_second',
                'created_at' => '2024-08-13 18:53:46',
                'updated_at' => '2024-08-13 18:53:46',
            ),
            16 => 
            array (
                'match_id' => 17,
                'team_first' => 'Manchester City',
                'team_second' => 'Newcastle United',
                'season' => '2023/2024',
                'tour' => 'tour 2',
                'match_date' => '2023-08-19',
                'coefficient_team_first' => 1.72,
                'coefficient_draw' => 4.1,
                'coefficient_team_second' => 5.0,
                'team_first_goals' => 1,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-13 18:55:47',
                'updated_at' => '2024-08-13 18:55:47',
            ),
            17 => 
            array (
                'match_id' => 18,
                'team_first' => 'Manchester City',
                'team_second' => 'Fulham',
                'season' => '2023/2024',
                'tour' => 'tour 4',
                'match_date' => '2023-09-02',
                'coefficient_team_first' => 1.19,
                'coefficient_draw' => 7.6,
                'coefficient_team_second' => 18.0,
                'team_first_goals' => 5,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-13 18:58:47',
                'updated_at' => '2024-08-13 18:58:47',
            ),
            18 => 
            array (
                'match_id' => 19,
                'team_first' => 'Manchester City',
                'team_second' => 'Brighton & Hove',
                'season' => '2023/2024',
                'tour' => 'tour 9',
                'match_date' => '2023-10-21',
                'coefficient_team_first' => 1.45,
                'coefficient_draw' => 5.3,
                'coefficient_team_second' => 6.7,
                'team_first_goals' => 2,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-13 19:03:43',
                'updated_at' => '2024-08-13 19:03:43',
            ),
            19 => 
            array (
                'match_id' => 20,
                'team_first' => 'Manchester City',
                'team_second' => 'Manchester United',
                'season' => '2023/2024',
                'tour' => 'tour 10',
                'match_date' => '2023-10-29',
                'coefficient_team_first' => 1.67,
                'coefficient_draw' => 4.4,
                'coefficient_team_second' => 5.0,
                'team_first_goals' => 3,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-13 19:05:24',
                'updated_at' => '2024-08-13 19:05:24',
            ),
            20 => 
            array (
                'match_id' => 21,
                'team_first' => 'Manchester City',
                'team_second' => 'Liverpool',
                'season' => '2023/2024',
                'tour' => 'tour 13',
                'match_date' => '2023-11-25',
                'coefficient_team_first' => 1.74,
                'coefficient_draw' => 4.3,
                'coefficient_team_second' => 4.55,
                'team_first_goals' => 1,
                'team_second_goals' => 1,
                'result' => 'draw',
                'created_at' => '2024-08-13 19:08:23',
                'updated_at' => '2024-08-13 19:08:23',
            ),
            21 => 
            array (
                'match_id' => 22,
                'team_first' => 'Manchester City',
                'team_second' => 'Tottenham',
                'season' => '2023/2024',
                'tour' => 'tour 14',
                'match_date' => '2023-12-03',
                'coefficient_team_first' => 1.31,
                'coefficient_draw' => 6.2,
                'coefficient_team_second' => 9.5,
                'team_first_goals' => 3,
                'team_second_goals' => 3,
                'result' => 'draw',
                'created_at' => '2024-08-13 19:09:49',
                'updated_at' => '2024-08-13 19:09:49',
            ),
            22 => 
            array (
                'match_id' => 23,
                'team_first' => 'Manchester City',
                'team_second' => 'Brentford',
                'season' => '2023/2024',
                'tour' => 'tour 18',
                'match_date' => '2024-02-20',
                'coefficient_team_first' => 1.22,
                'coefficient_draw' => 7.1,
                'coefficient_team_second' => 15.0,
                'team_first_goals' => 1,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-13 22:17:54',
                'updated_at' => '2024-08-13 22:17:54',
            ),
            23 => 
            array (
                'match_id' => 24,
                'team_first' => 'Manchester City',
                'team_second' => 'Everton',
                'season' => '2023/2024',
                'tour' => 'tour 19',
                'match_date' => '2023-12-27',
                'coefficient_team_first' => 1.65,
                'coefficient_draw' => 4.35,
                'coefficient_team_second' => 6.0,
                'team_first_goals' => 3,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-13 19:15:03',
                'updated_at' => '2024-08-13 19:15:03',
            ),
            24 => 
            array (
                'match_id' => 25,
                'team_first' => 'Manchester City',
                'team_second' => 'Brentford',
                'season' => '2023/2024',
                'tour' => 'tour 23',
                'match_date' => '2024-02-05',
                'coefficient_team_first' => 1.43,
                'coefficient_draw' => 5.1,
                'coefficient_team_second' => 7.6,
                'team_first_goals' => 3,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-13 19:35:12',
                'updated_at' => '2024-08-13 19:35:12',
            ),
            25 => 
            array (
                'match_id' => 26,
                'team_first' => 'Manchester City',
                'team_second' => 'Bournemouth',
                'season' => '2023/2024',
                'tour' => 'tour 26',
                'match_date' => '2024-02-24',
                'coefficient_team_first' => 1.46,
                'coefficient_draw' => 5.1,
                'coefficient_team_second' => 7.0,
                'team_first_goals' => 1,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:10:05',
                'updated_at' => '2024-08-14 14:10:05',
            ),
            26 => 
            array (
                'match_id' => 27,
                'team_first' => 'Manchester City',
                'team_second' => 'Manchester United',
                'season' => '2023/2024',
                'tour' => 'tour 27',
                'match_date' => '2024-03-03',
                'coefficient_team_first' => 1.28,
                'coefficient_draw' => 6.4,
                'coefficient_team_second' => 11.0,
                'team_first_goals' => 3,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:11:52',
                'updated_at' => '2024-08-14 14:11:52',
            ),
            27 => 
            array (
                'match_id' => 28,
                'team_first' => 'Manchester City',
                'team_second' => 'Liverpool',
                'season' => '2023/2024',
                'tour' => 'tour 28',
                'match_date' => '2024-03-10',
                'coefficient_team_first' => 2.31,
                'coefficient_draw' => 3.85,
                'coefficient_team_second' => 3.0,
                'team_first_goals' => 1,
                'team_second_goals' => 1,
                'result' => 'draw',
                'created_at' => '2024-08-14 14:13:09',
                'updated_at' => '2024-08-14 14:13:09',
            ),
            28 => 
            array (
                'match_id' => 29,
                'team_first' => 'Manchester City',
                'team_second' => 'Brighton & Hove',
                'season' => '2023/2024',
                'tour' => 'tour 29',
                'match_date' => '2024-03-10',
                'coefficient_team_first' => 1.5,
                'coefficient_draw' => 4.9,
                'coefficient_team_second' => 6.5,
                'team_first_goals' => 4,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:15:17',
                'updated_at' => '2024-08-14 14:15:17',
            ),
            29 => 
            array (
                'match_id' => 30,
                'team_first' => 'Manchester City',
                'team_second' => 'Arsenal',
                'season' => '2023/2024',
                'tour' => 'tour 30',
                'match_date' => '2024-03-31',
                'coefficient_team_first' => 1.94,
                'coefficient_draw' => 3.85,
                'coefficient_team_second' => 4.05,
                'team_first_goals' => 0,
                'team_second_goals' => 0,
                'result' => 'draw',
                'created_at' => '2024-08-14 14:16:25',
                'updated_at' => '2024-08-14 14:16:25',
            ),
            30 => 
            array (
                'match_id' => 31,
                'team_first' => 'Manchester City',
                'team_second' => 'Aston Villa',
                'season' => '2023/2024',
                'tour' => 'tour 31',
                'match_date' => '2024-04-03',
                'coefficient_team_first' => 1.33,
                'coefficient_draw' => 6.2,
                'coefficient_team_second' => 9.4,
                'team_first_goals' => 4,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:17:37',
                'updated_at' => '2024-08-14 14:17:37',
            ),
            31 => 
            array (
                'match_id' => 32,
                'team_first' => 'Manchester City',
                'team_second' => 'Crystal Palace',
                'season' => '2023/2024',
                'tour' => 'tour 32',
                'match_date' => '2024-04-06',
                'coefficient_team_first' => 1.4,
                'coefficient_draw' => 5.1,
                'coefficient_team_second' => 9.1,
                'team_first_goals' => 4,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:18:50',
                'updated_at' => '2024-08-14 14:18:50',
            ),
            32 => 
            array (
                'match_id' => 33,
                'team_first' => 'Manchester City',
                'team_second' => 'Luton Town',
                'season' => '2023/2024',
                'tour' => 'tour 33',
                'match_date' => '2024-04-13',
                'coefficient_team_first' => 2.45,
                'coefficient_draw' => 4.0,
                'coefficient_team_second' => 2.74,
                'team_first_goals' => 5,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:20:12',
                'updated_at' => '2024-08-14 14:20:12',
            ),
            33 => 
            array (
                'match_id' => 34,
                'team_first' => 'Manchester City',
                'team_second' => 'Tottenham',
                'season' => '2023/2024',
                'tour' => 'tour 34',
                'match_date' => '2024-05-14',
                'coefficient_team_first' => 1.39,
                'coefficient_draw' => 5.62,
                'coefficient_team_second' => 7.01,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:21:41',
                'updated_at' => '2024-08-14 14:21:41',
            ),
            34 => 
            array (
                'match_id' => 35,
                'team_first' => 'Manchester City',
                'team_second' => 'Forest',
                'season' => '2023/2024',
                'tour' => 'tour 35',
                'match_date' => '2024-04-28',
                'coefficient_team_first' => 1.35,
                'coefficient_draw' => 5.6,
                'coefficient_team_second' => 9.3,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:22:38',
                'updated_at' => '2024-08-14 14:22:38',
            ),
            35 => 
            array (
                'match_id' => 36,
                'team_first' => 'Manchester City',
                'team_second' => 'Wolverhampton',
                'season' => '2023/2024',
                'tour' => 'tour 36',
                'match_date' => '2024-05-04',
                'coefficient_team_first' => 1.14,
                'coefficient_draw' => 9.6,
                'coefficient_team_second' => 25.0,
                'team_first_goals' => 5,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:24:16',
                'updated_at' => '2024-08-14 14:24:16',
            ),
            36 => 
            array (
                'match_id' => 37,
                'team_first' => 'Manchester City',
                'team_second' => 'Fulham',
                'season' => '2023/2024',
                'tour' => 'tour 37',
                'match_date' => '2024-05-11',
                'coefficient_team_first' => 1.26,
                'coefficient_draw' => 6.6,
                'coefficient_team_second' => 12.5,
                'team_first_goals' => 4,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:25:44',
                'updated_at' => '2024-08-14 14:25:44',
            ),
            37 => 
            array (
                'match_id' => 38,
                'team_first' => 'Manchester City',
                'team_second' => 'West Ham United',
                'season' => '2023/2024',
                'tour' => 'tour 38',
                'match_date' => '2024-05-19',
                'coefficient_team_first' => 1.14,
                'coefficient_draw' => 9.9,
                'coefficient_team_second' => 20.03,
                'team_first_goals' => 3,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 14:27:10',
                'updated_at' => '2024-08-14 14:27:10',
            ),
            38 => 
            array (
                'match_id' => 39,
                'team_first' => 'Chelsea',
                'team_second' => 'Liverpool',
                'season' => '2023/2024',
                'tour' => 'tour 1',
                'match_date' => '2023-08-13',
                'coefficient_team_first' => 2.99,
                'coefficient_draw' => 3.75,
                'coefficient_team_second' => 2.48,
                'team_first_goals' => 1,
                'team_second_goals' => 1,
                'result' => 'draw',
                'created_at' => '2024-08-14 18:54:30',
                'updated_at' => '2024-08-14 18:54:30',
            ),
            39 => 
            array (
                'match_id' => 40,
                'team_first' => 'West Ham United',
                'team_second' => 'Chelsea',
                'season' => '2023/2024',
                'tour' => 'tour 2',
                'match_date' => '2023-08-20',
                'coefficient_team_first' => 3.8,
                'coefficient_draw' => 3.65,
                'coefficient_team_second' => 2.04,
                'team_first_goals' => 3,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:44:03',
                'updated_at' => '2024-08-14 19:44:03',
            ),
            40 => 
            array (
                'match_id' => 41,
                'team_first' => 'Luton Town',
                'team_second' => 'Chelsea',
                'season' => '2023/2024',
                'tour' => 'tour 3',
                'match_date' => '2023-08-25',
                'coefficient_team_first' => 14.0,
                'coefficient_draw' => 6.4,
                'coefficient_team_second' => 1.25,
                'team_first_goals' => 0,
                'team_second_goals' => 3,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:02:53',
                'updated_at' => '2024-08-14 19:02:53',
            ),
            41 => 
            array (
                'match_id' => 42,
                'team_first' => 'Chelsea',
                'team_second' => 'Forest',
                'season' => '2023/2024',
                'tour' => 'tour 4',
                'match_date' => '2023-09-02',
                'coefficient_team_first' => 1.4,
                'coefficient_draw' => 5.1,
                'coefficient_team_second' => 8.4,
                'team_first_goals' => 0,
                'team_second_goals' => 1,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:04:09',
                'updated_at' => '2024-08-14 19:04:09',
            ),
            42 => 
            array (
                'match_id' => 43,
                'team_first' => 'Bournemouth',
                'team_second' => 'Chelsea',
                'season' => '2023/2024',
                'tour' => 'tour 5',
                'match_date' => '2023-09-17',
                'coefficient_team_first' => 4.45,
                'coefficient_draw' => 4.0,
                'coefficient_team_second' => 1.81,
                'team_first_goals' => 0,
                'team_second_goals' => 0,
                'result' => 'draw',
                'created_at' => '2024-08-14 19:05:40',
                'updated_at' => '2024-08-14 19:05:40',
            ),
            43 => 
            array (
                'match_id' => 44,
                'team_first' => 'Chelsea',
                'team_second' => 'Aston Villa',
                'season' => '2023/2024',
                'tour' => 'tour 6',
                'match_date' => '2023-09-24',
                'coefficient_team_first' => 1.94,
                'coefficient_draw' => 3.8,
                'coefficient_team_second' => 4.05,
                'team_first_goals' => 0,
                'team_second_goals' => 1,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:06:58',
                'updated_at' => '2024-08-14 19:06:58',
            ),
            44 => 
            array (
                'match_id' => 45,
                'team_first' => 'Chelsea',
                'team_second' => 'Fulham',
                'season' => '2023/2024',
                'tour' => 'tour 7',
                'match_date' => '2023-10-02',
                'coefficient_team_first' => 2.03,
                'coefficient_draw' => 3.55,
                'coefficient_team_second' => 3.95,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:08:06',
                'updated_at' => '2024-08-14 19:08:06',
            ),
            45 => 
            array (
                'match_id' => 46,
                'team_first' => 'Chelsea',
                'team_second' => 'Burnley',
                'season' => '2023/2024',
                'tour' => 'tour 8',
                'match_date' => '2023-10-07',
                'coefficient_team_first' => 1.72,
                'coefficient_draw' => 4.05,
                'coefficient_team_second' => 5.0,
                'team_first_goals' => 4,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:09:21',
                'updated_at' => '2024-08-14 19:09:21',
            ),
            46 => 
            array (
                'match_id' => 47,
                'team_first' => 'Chelsea',
                'team_second' => 'Arsenal',
                'season' => '2023/2024',
                'tour' => 'tour 9',
                'match_date' => '2023-10-21',
                'coefficient_team_first' => 3.15,
                'coefficient_draw' => 3.5,
                'coefficient_team_second' => 2.37,
                'team_first_goals' => 2,
                'team_second_goals' => 2,
                'result' => 'draw',
                'created_at' => '2024-08-14 19:10:23',
                'updated_at' => '2024-08-14 19:10:23',
            ),
            47 => 
            array (
                'match_id' => 48,
                'team_first' => 'Chelsea',
                'team_second' => 'Brentford',
                'season' => '2023/2024',
                'tour' => 'tour 10',
                'match_date' => '2023-10-28',
                'coefficient_team_first' => 1.64,
                'coefficient_draw' => 4.35,
                'coefficient_team_second' => 5.3,
                'team_first_goals' => 0,
                'team_second_goals' => 2,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:11:32',
                'updated_at' => '2024-08-14 19:11:32',
            ),
            48 => 
            array (
                'match_id' => 49,
                'team_first' => 'Chelsea',
                'team_second' => 'Tottenham',
                'season' => '2023/2024',
                'tour' => 'tour 11',
                'match_date' => '2023-11-06',
                'coefficient_team_first' => 3.35,
                'coefficient_draw' => 3.85,
                'coefficient_team_second' => 2.14,
                'team_first_goals' => 4,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:13:33',
                'updated_at' => '2024-08-14 19:13:33',
            ),
            49 => 
            array (
                'match_id' => 50,
                'team_first' => 'Chelsea',
                'team_second' => 'Newcastle United',
                'season' => '2023/2024',
                'tour' => 'tour 13',
                'match_date' => '2023-11-25',
                'coefficient_team_first' => 2.73,
                'coefficient_draw' => 3.55,
                'coefficient_team_second' => 2.65,
                'team_first_goals' => 1,
                'team_second_goals' => 4,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:14:57',
                'updated_at' => '2024-08-14 19:14:57',
            ),
            50 => 
            array (
                'match_id' => 51,
                'team_first' => 'Chelsea',
                'team_second' => 'Brighton & Hove',
                'season' => '2023/2024',
                'tour' => 'tour 14',
                'match_date' => '2023-12-03',
                'coefficient_team_first' => 1.72,
                'coefficient_draw' => 4.3,
                'coefficient_team_second' => 4.65,
                'team_first_goals' => 3,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:16:16',
                'updated_at' => '2024-08-14 19:16:16',
            ),
            51 => 
            array (
                'match_id' => 52,
                'team_first' => 'Chelsea',
                'team_second' => 'Manchester United',
                'season' => '2023/2024',
                'tour' => 'tour 15',
                'match_date' => '2023-12-06',
                'coefficient_team_first' => 2.52,
                'coefficient_draw' => 3.75,
                'coefficient_team_second' => 2.95,
                'team_first_goals' => 1,
                'team_second_goals' => 2,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:17:37',
                'updated_at' => '2024-08-14 19:17:37',
            ),
            52 => 
            array (
                'match_id' => 53,
                'team_first' => 'Chelsea',
                'team_second' => 'Everton',
                'season' => '2023/2024',
                'tour' => 'tour 16',
                'match_date' => '2023-12-10',
                'coefficient_team_first' => 2.36,
                'coefficient_draw' => 3.6,
                'coefficient_team_second' => 3.05,
                'team_first_goals' => 0,
                'team_second_goals' => 2,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:18:36',
                'updated_at' => '2024-08-14 19:18:36',
            ),
            53 => 
            array (
                'match_id' => 54,
                'team_first' => 'Chelsea',
                'team_second' => 'Sheffield United',
                'season' => '2023/2024',
                'tour' => 'tour 17',
                'match_date' => '2023-12-16',
                'coefficient_team_first' => 1.27,
                'coefficient_draw' => 6.2,
                'coefficient_team_second' => 12.5,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:20:12',
                'updated_at' => '2024-08-14 19:20:12',
            ),
            54 => 
            array (
                'match_id' => 55,
                'team_first' => 'Chelsea',
                'team_second' => 'Wolverhampton',
                'season' => '2023/2024',
                'tour' => 'tour 18',
                'match_date' => '2023-12-24',
                'coefficient_team_first' => 1.98,
                'coefficient_draw' => 3.75,
                'coefficient_team_second' => 3.95,
                'team_first_goals' => 1,
                'team_second_goals' => 2,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:21:17',
                'updated_at' => '2024-08-14 19:21:17',
            ),
            55 => 
            array (
                'match_id' => 56,
                'team_first' => 'Chelsea',
                'team_second' => 'Crystal Palace',
                'season' => '2023/2024',
                'tour' => 'tour 19',
                'match_date' => '2023-12-27',
                'coefficient_team_first' => 1.79,
                'coefficient_draw' => 3.8,
                'coefficient_team_second' => 4.9,
                'team_first_goals' => 2,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:22:29',
                'updated_at' => '2024-08-14 19:22:29',
            ),
            56 => 
            array (
                'match_id' => 57,
                'team_first' => 'Chelsea',
                'team_second' => 'Luton Town',
                'season' => '2023/2024',
                'tour' => 'tour 20',
                'match_date' => '2023-12-30',
                'coefficient_team_first' => 1.65,
                'coefficient_draw' => 4.25,
                'coefficient_team_second' => 5.4,
                'team_first_goals' => 3,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:23:21',
                'updated_at' => '2024-08-14 19:23:21',
            ),
            57 => 
            array (
                'match_id' => 58,
                'team_first' => 'Chelsea',
                'team_second' => 'Fulham',
                'season' => '2023/2024',
                'tour' => 'tour 21',
                'match_date' => '2024-01-13',
                'coefficient_team_first' => 1.66,
                'coefficient_draw' => 4.2,
                'coefficient_team_second' => 5.3,
                'team_first_goals' => 1,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:25:43',
                'updated_at' => '2024-08-14 19:25:43',
            ),
            58 => 
            array (
                'match_id' => 59,
                'team_first' => 'Chelsea',
                'team_second' => 'Liverpool',
                'season' => '2023/2024',
                'tour' => 'tour 22',
                'match_date' => '2024-01-31',
                'coefficient_team_first' => 5.3,
                'coefficient_draw' => 4.7,
                'coefficient_team_second' => 1.65,
                'team_first_goals' => 1,
                'team_second_goals' => 4,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:25:08',
                'updated_at' => '2024-08-14 19:25:08',
            ),
            59 => 
            array (
                'match_id' => 60,
                'team_first' => 'Wolverhampton',
                'team_second' => 'Chelsea',
                'season' => '2023/2024',
                'tour' => 'tour 23',
                'match_date' => '2024-02-04',
                'coefficient_team_first' => 1.66,
                'coefficient_draw' => 4.2,
                'coefficient_team_second' => 5.3,
                'team_first_goals' => 4,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:28:08',
                'updated_at' => '2024-08-14 19:28:08',
            ),
            60 => 
            array (
                'match_id' => 61,
                'team_first' => 'Chelsea',
                'team_second' => 'Crystal Palace',
                'season' => '2023/2024',
                'tour' => 'tour 24',
                'match_date' => '2024-02-12',
                'coefficient_team_first' => 1.79,
                'coefficient_draw' => 3.9,
                'coefficient_team_second' => 4.75,
                'team_first_goals' => 3,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:27:52',
                'updated_at' => '2024-08-14 19:27:52',
            ),
            61 => 
            array (
                'match_id' => 62,
                'team_first' => 'Chelsea',
                'team_second' => 'Tottenham',
                'season' => '2023/2024',
                'tour' => 'tour 26',
                'match_date' => '2024-05-02',
                'coefficient_team_first' => 2.23,
                'coefficient_draw' => 4.05,
                'coefficient_team_second' => 2.95,
                'team_first_goals' => 2,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:29:24',
                'updated_at' => '2024-08-14 19:29:24',
            ),
            62 => 
            array (
                'match_id' => 63,
                'team_first' => 'Chelsea',
                'team_second' => 'Brentford',
                'season' => '2023/2024',
                'tour' => 'tour 27',
                'match_date' => '2024-03-02',
                'coefficient_team_first' => 2.2,
                'coefficient_draw' => 3.85,
                'coefficient_team_second' => 3.2,
                'team_first_goals' => 2,
                'team_second_goals' => 2,
                'result' => 'draw',
                'created_at' => '2024-08-14 19:30:25',
                'updated_at' => '2024-08-14 19:30:25',
            ),
            63 => 
            array (
                'match_id' => 64,
                'team_first' => 'Chelsea',
                'team_second' => 'Newcastle United',
                'season' => '2023/2024',
                'tour' => 'tour 28',
                'match_date' => '2024-03-11',
                'coefficient_team_first' => 1.92,
                'coefficient_draw' => 4.1,
                'coefficient_team_second' => 3.8,
                'team_first_goals' => 3,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:31:25',
                'updated_at' => '2024-08-14 19:31:25',
            ),
            64 => 
            array (
                'match_id' => 65,
                'team_first' => 'Chelsea',
                'team_second' => 'Arsenal',
                'season' => '2023/2024',
                'tour' => 'tour 29',
                'match_date' => '2024-04-23',
                'coefficient_team_first' => 5.9,
                'coefficient_draw' => 4.55,
                'coefficient_team_second' => 1.57,
                'team_first_goals' => 0,
                'team_second_goals' => 5,
                'result' => 'win_second',
                'created_at' => '2024-08-14 19:32:23',
                'updated_at' => '2024-08-14 19:32:23',
            ),
            65 => 
            array (
                'match_id' => 66,
                'team_first' => 'Chelsea',
                'team_second' => 'Burnley',
                'season' => '2023/2024',
                'tour' => 'tour 30',
                'match_date' => '2024-03-30',
                'coefficient_team_first' => 1.33,
                'coefficient_draw' => 5.9,
                'coefficient_team_second' => 9.9,
                'team_first_goals' => 2,
                'team_second_goals' => 2,
                'result' => 'draw',
                'created_at' => '2024-08-14 19:33:26',
                'updated_at' => '2024-08-14 19:33:26',
            ),
            66 => 
            array (
                'match_id' => 67,
                'team_first' => 'Chelsea',
                'team_second' => 'Manchester United',
                'season' => '2023/2024',
                'tour' => 'tour 31',
                'match_date' => '2024-04-04',
                'coefficient_team_first' => 2.0,
                'coefficient_draw' => 4.15,
                'coefficient_team_second' => 3.55,
                'team_first_goals' => 4,
                'team_second_goals' => 3,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:34:27',
                'updated_at' => '2024-08-14 19:34:27',
            ),
            67 => 
            array (
                'match_id' => 68,
                'team_first' => 'Chelsea',
                'team_second' => 'Sheffield United',
                'season' => '2023/2024',
                'tour' => 'tour 32',
                'match_date' => '2024-04-07',
                'coefficient_team_first' => 1.44,
                'coefficient_draw' => 5.4,
                'coefficient_team_second' => 7.2,
                'team_first_goals' => 2,
                'team_second_goals' => 2,
                'result' => 'draw',
                'created_at' => '2024-08-14 19:35:28',
                'updated_at' => '2024-08-14 19:35:28',
            ),
            68 => 
            array (
                'match_id' => 69,
                'team_first' => 'Chelsea',
                'team_second' => 'Everton',
                'season' => '2023/2024',
                'tour' => 'tour 33',
                'match_date' => '2024-04-15',
                'coefficient_team_first' => 1.77,
                'coefficient_draw' => 4.2,
                'coefficient_team_second' => 4.6,
                'team_first_goals' => 6,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:36:37',
                'updated_at' => '2024-08-14 19:36:37',
            ),
            69 => 
            array (
                'match_id' => 70,
                'team_first' => 'Chelsea',
                'team_second' => 'Brighton & Hove',
                'season' => '2023/2024',
                'tour' => 'tour 34',
                'match_date' => '2024-05-15',
                'coefficient_team_first' => 2.07,
                'coefficient_draw' => 4.05,
                'coefficient_team_second' => 3.4,
                'team_first_goals' => 2,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:37:39',
                'updated_at' => '2024-08-14 19:37:39',
            ),
            70 => 
            array (
                'match_id' => 71,
                'team_first' => 'Chelsea',
                'team_second' => 'Aston Villa',
                'season' => '2023/2024',
                'tour' => 'tour 35',
                'match_date' => '2024-04-27',
                'coefficient_team_first' => 3.0,
                'coefficient_draw' => 3.85,
                'coefficient_team_second' => 2.3,
                'team_first_goals' => 2,
                'team_second_goals' => 2,
                'result' => 'draw',
                'created_at' => '2024-08-14 19:38:41',
                'updated_at' => '2024-08-14 19:38:41',
            ),
            71 => 
            array (
                'match_id' => 72,
                'team_first' => 'Chelsea',
                'team_second' => 'West Ham United',
                'season' => '2023/2024',
                'tour' => 'tour 36',
                'match_date' => '2024-05-05',
                'coefficient_team_first' => 1.69,
                'coefficient_draw' => 4.6,
                'coefficient_team_second' => 4.6,
                'team_first_goals' => 5,
                'team_second_goals' => 0,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:39:57',
                'updated_at' => '2024-08-14 19:39:57',
            ),
            72 => 
            array (
                'match_id' => 73,
                'team_first' => 'Chelsea',
                'team_second' => 'Forest',
                'season' => '2023/2024',
                'tour' => 'tour 37',
                'match_date' => '2024-05-11',
                'coefficient_team_first' => 2.02,
                'coefficient_draw' => 4.0,
                'coefficient_team_second' => 3.6,
                'team_first_goals' => 3,
                'team_second_goals' => 2,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:41:17',
                'updated_at' => '2024-08-14 19:41:17',
            ),
            73 => 
            array (
                'match_id' => 74,
                'team_first' => 'Chelsea',
                'team_second' => 'Bournemouth',
                'season' => '2023/2024',
                'tour' => 'tour 38',
                'match_date' => '2024-05-19',
                'coefficient_team_first' => 1.5,
                'coefficient_draw' => 5.1,
                'coefficient_team_second' => 5.9,
                'team_first_goals' => 2,
                'team_second_goals' => 1,
                'result' => 'win_first',
                'created_at' => '2024-08-14 19:42:18',
                'updated_at' => '2024-08-14 19:42:18',
            ),
        ));
        
        
    }
}